### ISSUE TITLE
pre-Open Source checklist

### ISSUE THREAD

**Issue by malave** [samtecspg/conveyor#34]
Just adding a few items here, will add/remove later when I give it some more thought:
- [x] [Readme] Explain that is it all about
- [x] [Readme] Explain shortcomings or list of things that we know we can improve
- [ ] [Code] Refactor `api/models/flow.model.js` and `api/models/flow-template.model.js` to have a similar structure
- [x] [Code] Complete Swagger documentation #28 
- [x] [Code] Revise error message handling (sent to the user) and logging (on console) (or add to to do list)
- [x] [Code] Update `package.json` description and tags for better SEO (or add to to do list)
- [x] [Readme] mention the URL parameter (either that the name should be `url` or what we decide to use in #32 
- [ ] [Code] Skip metrics when running tests

**Comment by milutz** [comment]
@malave is this one done now? (if so can you close?)
